### ISSUE TITLE
Compatibilidade com o Ventura

### ISSUE THREAD

**Issue by edulemasson** [luchina-gabriel/EFI-X99-HUANANZHI-F8-INTEL-XEON-V3-RX-580-8GB#1]
No README.md diz ser compatível com as seguintes versões do MacOs:

macOS Big Sur, macOS Catalina and macOS Monterey

O suporte ao Ventura deveria ser incluído nesta lista, certo ?

Parabéns pelo trabalho de divulgação e curadoria de conteúdo

**Comment by luchina-gabriel** [comment]
Oi Eduardo, blz? 

Vlw pelo feedback!

Para rodar versões mais novas, precisa atualizar o repositório.

Fiz uma LIVE mega completa ensinando a criar toda a EFI e tudo mais, aqui:
https://youtu.be/5FVxZDXr98o
